name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven

    # SETUP Maven
    - name: Build with Maven
      run: mvn clean install

    # SETUP Docker
    - name: Build & Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ${{ secrets.REPOSITORY_DOCKER_HUB }}
        tags: latest
        registry: docker.io
        username: ${{ secrets.USERNAME_DOCKER_HUB }}
        password: ${{ secrets. PASSWORD_DOCKER_HUB }}
    
    #AWS Deploy 

    - name: Deploy Using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_AWS_EC2 }}
        username: ${{ secrets.USERNAME_AWS_EC2 }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          echo "========= stop container ========";
          docker stop ${{ secrets.CONTAINER_NAME }}
          echo "========= remove container ========";
          docker rm ${{ secrets.CONTAINER_NAME }}
          echo "========= hapus image ========";
          docker rmi -f ${{ secrets.REPOSITORY_DOCKER_HUB }}:latest
          echo "========= pull image ========";
          docker pull ${{ secrets.REPOSITORY_DOCKER_HUB }}:latest
          echo "========= run image ========";
          docker run -d -p 80:8080 --name ${{ secrets.CONTAINER_NAME }} ${{ secrets.REPOSITORY_DOCKER_HUB }}